
"""add_budget_type_and_nullable_category

Revision ID: 370a47fce50c
Revises: ebb54091bc15
Create Date: 2026-05-02 11:20:19.937701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '370a47fce50c'
down_revision: Union[str, None] = 'ebb54091bc15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Add budget_type with server default for existing rows
    op.add_column('budgets', sa.Column('budget_type', sa.String(length=20), nullable=True))
    op.execute("UPDATE budgets SET budget_type = 'category' WHERE budget_type IS NULL")
    op.alter_column('budgets', 'budget_type', nullable=False)
    op.alter_column('budgets', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('budgets', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('budgets', 'budget_type')
    # ### end Alembic commands ###
