
"""add_accounts_and_credit_cards

Revision ID: de3006439209
Revises: 0003
Create Date: 2026-05-03 18:14:37.590134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'de3006439209'
down_revision: Union[str, None] = '0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('bank', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('accounts_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('accounts_pkey'))
    )
    op.create_index(op.f('accounts_user_id_idx'), 'accounts', ['user_id'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('conversations_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('conversations_pkey'))
    )
    op.create_index(op.f('conversations_user_id_idx'), 'conversations', ['user_id'], unique=False)
    op.create_table('credit_cards',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('issuer', sa.String(length=50), nullable=False),
    sa.Column('limit', sa.Float(), nullable=False),
    sa.Column('closing_day', sa.Integer(), nullable=False),
    sa.Column('due_day', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('credit_cards_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('credit_cards_pkey'))
    )
    op.create_index(op.f('credit_cards_user_id_idx'), 'credit_cards', ['user_id'], unique=False)
    op.create_table('conversation_shares',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('shared_by', sa.UUID(), nullable=False),
    sa.Column('shared_with', sa.UUID(), nullable=True),
    sa.Column('share_token', sa.String(length=64), nullable=True),
    sa.Column('permission', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('conversation_shares_conversation_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shared_by'], ['users.id'], name=op.f('conversation_shares_shared_by_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shared_with'], ['users.id'], name=op.f('conversation_shares_shared_with_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('conversation_shares_pkey')),
    sa.UniqueConstraint('conversation_id', 'shared_with', name='uq_share_conv_user'),
    sa.UniqueConstraint('share_token', name=op.f('conversation_shares_share_token_key'))
    )
    op.create_index(op.f('conversation_shares_conversation_id_idx'), 'conversation_shares', ['conversation_id'], unique=False)
    op.create_index(op.f('conversation_shares_shared_with_idx'), 'conversation_shares', ['shared_with'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('messages_conversation_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('messages_pkey'))
    )
    op.create_index(op.f('messages_conversation_id_idx'), 'messages', ['conversation_id'], unique=False)
    op.create_table('chat_files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('file_type', sa.String(length=20), nullable=False),
    sa.Column('parsed_content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name=op.f('chat_files_message_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('chat_files_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('chat_files_pkey'))
    )
    op.create_index(op.f('chat_files_user_id_idx'), 'chat_files', ['user_id'], unique=False)
    op.create_table('message_ratings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('rating IN (1, -1)', name=op.f('message_ratings_ck_rating_value_check')),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name=op.f('message_ratings_message_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('message_ratings_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('message_ratings_pkey')),
    sa.UniqueConstraint('message_id', 'user_id', name='uq_message_user_rating')
    )
    op.create_index(op.f('message_ratings_message_id_idx'), 'message_ratings', ['message_id'], unique=False)
    op.create_index(op.f('message_ratings_user_id_idx'), 'message_ratings', ['user_id'], unique=False)
    op.create_table('tool_calls',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('tool_call_id', sa.String(length=100), nullable=False),
    sa.Column('tool_name', sa.String(length=100), nullable=False),
    sa.Column('args', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name=op.f('tool_calls_message_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('tool_calls_pkey'))
    )
    op.create_index(op.f('tool_calls_message_id_idx'), 'tool_calls', ['message_id'], unique=False)
    op.add_column('budgets', sa.Column('user_uuid', sa.UUID(), nullable=True))
    op.create_index(op.f('budgets_user_uuid_idx'), 'budgets', ['user_uuid'], unique=False)
    op.create_foreign_key(op.f('budgets_user_uuid_fkey'), 'budgets', 'users', ['user_uuid'], ['id'], ondelete='CASCADE')
    op.add_column('goals', sa.Column('user_uuid', sa.UUID(), nullable=True))
    op.create_index(op.f('goals_user_uuid_idx'), 'goals', ['user_uuid'], unique=False)
    op.create_foreign_key(op.f('goals_user_uuid_fkey'), 'goals', 'users', ['user_uuid'], ['id'], ondelete='CASCADE')
    op.alter_column('phone_users', 'phone_number',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=80),
               existing_nullable=False)
    op.add_column('reports', sa.Column('user_uuid', sa.UUID(), nullable=True))
    op.create_index(op.f('reports_user_uuid_idx'), 'reports', ['user_uuid'], unique=False)
    op.create_foreign_key(op.f('reports_user_uuid_fkey'), 'reports', 'users', ['user_uuid'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_transactions_user_uuid'), table_name='transactions')
    op.create_index(op.f('transactions_user_uuid_idx'), 'transactions', ['user_uuid'], unique=False)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index(op.f('users_email_idx'), 'users', ['email'], unique=True)
    op.create_unique_constraint(op.f('users_google_id_key'), 'users', ['google_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('users_google_id_key'), 'users', type_='unique')
    op.drop_index(op.f('users_email_idx'), table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.drop_index(op.f('transactions_user_uuid_idx'), table_name='transactions')
    op.create_index(op.f('ix_transactions_user_uuid'), 'transactions', ['user_uuid'], unique=False)
    op.drop_constraint(op.f('reports_user_uuid_fkey'), 'reports', type_='foreignkey')
    op.drop_index(op.f('reports_user_uuid_idx'), table_name='reports')
    op.drop_column('reports', 'user_uuid')
    op.alter_column('phone_users', 'phone_number',
               existing_type=sa.String(length=80),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.drop_constraint(op.f('goals_user_uuid_fkey'), 'goals', type_='foreignkey')
    op.drop_index(op.f('goals_user_uuid_idx'), table_name='goals')
    op.drop_column('goals', 'user_uuid')
    op.drop_constraint(op.f('budgets_user_uuid_fkey'), 'budgets', type_='foreignkey')
    op.drop_index(op.f('budgets_user_uuid_idx'), table_name='budgets')
    op.drop_column('budgets', 'user_uuid')
    op.drop_index(op.f('tool_calls_message_id_idx'), table_name='tool_calls')
    op.drop_table('tool_calls')
    op.drop_index(op.f('message_ratings_user_id_idx'), table_name='message_ratings')
    op.drop_index(op.f('message_ratings_message_id_idx'), table_name='message_ratings')
    op.drop_table('message_ratings')
    op.drop_index(op.f('chat_files_user_id_idx'), table_name='chat_files')
    op.drop_table('chat_files')
    op.drop_index(op.f('messages_conversation_id_idx'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('conversation_shares_shared_with_idx'), table_name='conversation_shares')
    op.drop_index(op.f('conversation_shares_conversation_id_idx'), table_name='conversation_shares')
    op.drop_table('conversation_shares')
    op.drop_index(op.f('credit_cards_user_id_idx'), table_name='credit_cards')
    op.drop_table('credit_cards')
    op.drop_index(op.f('conversations_user_id_idx'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('accounts_user_id_idx'), table_name='accounts')
    op.drop_table('accounts')
    # ### end Alembic commands ###
