
"""make_goals_budgets_user_id_nullable

Revision ID: 020638762158
Revises: e8f1a2b3c4d5
Create Date: 2026-05-07 20:47:46.473026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '020638762158'
down_revision: Union[str, None] = 'e8f1a2b3c4d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('budgets', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('goals', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('phone_users_merged_into_user_id_idx'), 'phone_users', ['merged_into_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('phone_users_merged_into_user_id_idx'), table_name='phone_users')
    op.alter_column('goals', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('budgets', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
