
"""initial_migration

Revision ID: ebb54091bc15
Revises: 
Create Date: 2026-04-30 23:53:18.079965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ebb54091bc15'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('phone_users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('preferences', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('financial_profile', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('telegram_chat_id', sa.String(length=50), nullable=True),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('phone_users_pkey'))
    )
    op.create_index(op.f('phone_users_phone_number_idx'), 'phone_users', ['phone_number'], unique=True)
    op.create_index(op.f('phone_users_telegram_chat_id_idx'), 'phone_users', ['telegram_chat_id'], unique=True)
    op.create_table('agent_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('agent_name', sa.String(length=50), nullable=False),
    sa.Column('request_payload', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('response_payload', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['phone_users.id'], name=op.f('agent_logs_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('agent_logs_pkey'))
    )
    op.create_index(op.f('agent_logs_user_id_idx'), 'agent_logs', ['user_id'], unique=False)
    op.create_table('categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('parent_category_id', sa.Integer(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parent_category_id'], ['categories.id'], name=op.f('categories_parent_category_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['phone_users.id'], name=op.f('categories_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('categories_pkey'))
    )
    op.create_index(op.f('categories_user_id_idx'), 'categories', ['user_id'], unique=False)
    op.create_table('goals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('target_amount', sa.Float(), nullable=False),
    sa.Column('current_amount', sa.Float(), nullable=False),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['phone_users.id'], name=op.f('goals_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('goals_pkey'))
    )
    op.create_index(op.f('goals_user_id_idx'), 'goals', ['user_id'], unique=False)
    op.create_table('phone_conversations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('last_intent', sa.String(length=50), nullable=True),
    sa.Column('context_json', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('message_history', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['phone_users.id'], name=op.f('phone_conversations_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('phone_conversations_pkey'))
    )
    op.create_index(op.f('phone_conversations_user_id_idx'), 'phone_conversations', ['user_id'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('file_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['phone_users.id'], name=op.f('reports_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('reports_pkey'))
    )
    op.create_index(op.f('reports_user_id_idx'), 'reports', ['user_id'], unique=False)
    op.create_table('budgets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('period', sa.String(length=20), nullable=False),
    sa.Column('total_limit', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('budgets_category_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['phone_users.id'], name=op.f('budgets_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('budgets_pkey'))
    )
    op.create_index(op.f('budgets_user_id_idx'), 'budgets', ['user_id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_format', sa.String(length=20), nullable=False),
    sa.Column('transaction_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('raw_input', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('transactions_category_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['phone_users.id'], name=op.f('transactions_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('transactions_pkey'))
    )
    op.create_index(op.f('transactions_category_id_idx'), 'transactions', ['category_id'], unique=False)
    op.create_index(op.f('transactions_user_id_idx'), 'transactions', ['user_id'], unique=False)
    op.create_table('budget_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('budget_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('limit_amount', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['budget_id'], ['budgets.id'], name=op.f('budget_items_budget_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('budget_items_category_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('budget_items_pkey'))
    )
    op.create_index(op.f('budget_items_budget_id_idx'), 'budget_items', ['budget_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('budget_items_budget_id_idx'), table_name='budget_items')
    op.drop_table('budget_items')
    op.drop_index(op.f('transactions_user_id_idx'), table_name='transactions')
    op.drop_index(op.f('transactions_category_id_idx'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('budgets_user_id_idx'), table_name='budgets')
    op.drop_table('budgets')
    op.drop_index(op.f('reports_user_id_idx'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('phone_conversations_user_id_idx'), table_name='phone_conversations')
    op.drop_table('phone_conversations')
    op.drop_index(op.f('goals_user_id_idx'), table_name='goals')
    op.drop_table('goals')
    op.drop_index(op.f('categories_user_id_idx'), table_name='categories')
    op.drop_table('categories')
    op.drop_index(op.f('agent_logs_user_id_idx'), table_name='agent_logs')
    op.drop_table('agent_logs')
    op.drop_index(op.f('phone_users_telegram_chat_id_idx'), table_name='phone_users')
    op.drop_index(op.f('phone_users_phone_number_idx'), table_name='phone_users')
    op.drop_table('phone_users')
    # ### end Alembic commands ###
